name: PyTest Ubuntu

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }} 
    
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install System Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y python3-opengl xvfb

        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: 3.12

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-xdist pytest-cov
            pip install -r requirements.txt

        - name: Run Tests with Coverage on Ubuntu
          run: xvfb-run -s "-screen 0 1400x900x24" pytest -n auto -v --cov=jaxvmas --cov-report=xml jaxvmas
